import { moneyCompact } from "@/lib/currency";

// Equipment used by brands and manufacturers to fill, seal, code and label packs.
// Price bands combine published Indian supplier prices and current market guides.
// They are indicative planning ranges; final model, warranty, freight, installation and GST are quoted separately.

export type MachineCategory = "sealing" | "coding" | "filling" | "automatic";

export type Machine = {
  slug: string;
  name: string;
  category: MachineCategory;
  priceFrom: number;
  priceTo: number;
  output: string;
  bestFor: string;
  summary: string;
  features: string[];
  image: string;
  imageAlt: string;
  sourceUrl: string;
  /** What the machine does to the pack, shown before the first worksWith item ("Seals", "Fills"…). */
  packVerb: string;
  /** Product codes of packaging this machine runs. The first one is featured on the card. */
  worksWith: string[];
};

export const MACHINE_CATEGORIES: Array<{ id: MachineCategory; label: string; blurb: string }> = [
  { id: "sealing", label: "Seal", blurb: "Close pouches and bottles after filling." },
  { id: "filling", label: "Fill", blurb: "Dose dry products and liquids into the pack." },
  { id: "coding", label: "Code & label", blurb: "Add batch, date, MRP and product labels." },
  { id: "automatic", label: "Automate", blurb: "Form, fill and seal from printed rollstock." },
];

export const MACHINES: Machine[] = [
  {
    slug: "hand-impulse-sealer",
    name: "Hand Impulse Sealer",
    category: "sealing",
    priceFrom: 3000,
    priceTo: 15000,
    output: "Manual, one seal per press",
    bestFor: "First-time and low-volume sealing of pouches and poly bags",
    summary: "Press the arm down and a timed pulse heats the element, sealing the pouch mouth without keeping the bar hot between seals.",
    features: ["Seal time set on a dial", "Sizes from 8 to 16 inch seal length", "Replaceable heating element and PTFE tape"],
    image: "/images/machinery/catalog/impulse-sealer.webp",
    imageAlt: "Hand-operated impulse sealer with pull-down sealing arm",
    sourceUrl: "https://dir.indiamart.com/impcat/impulse-sealer.html",
    packVerb: "Seals",
    worksWith: ["FP-101", "FP-106", "FP-115"],
  },
  {
    slug: "horizontal-band-sealer",
    name: "Horizontal Continuous Band Sealer",
    category: "sealing",
    priceFrom: 8450,
    priceTo: 20000,
    output: "Continuous conveyor sealing",
    bestFor: "Dry, lightweight pouches that can lie flat while sealing",
    summary: "Moves filled pouches through heated bands for repeatable sealing without stopping between packs.",
    features: ["Adjustable conveyor speed", "Optional coding wheel", "For pre-made pouches and bags"],
    image: "/images/machinery/catalog/horizontal-band-sealer.webp",
    imageAlt: "Representative horizontal continuous band sealing machine",
    sourceUrl: "https://www.newvisionmachines.com/shop/horizontal-continuous-band-sealer-ms-fr900",
    packVerb: "Seals",
    worksWith: ["FP-101", "FP-106", "FP-109"],
  },
  {
    slug: "vertical-band-sealer",
    name: "Vertical Continuous Band Sealer",
    category: "sealing",
    priceFrom: 30000,
    priceTo: 50000,
    output: "Upright conveyor sealing",
    bestFor: "Liquids, powders and products that must remain upright",
    summary: "Supports the filled pack vertically while it passes through a controlled continuous seal.",
    features: ["Height-adjustable sealing head", "Stainless-steel options", "Digital temperature control"],
    image: "/images/machinery/catalog/vertical-band-sealer.webp",
    imageAlt: "Representative vertical continuous band sealing machine",
    sourceUrl: "https://www.newvisionmachines.com/shop/stainless-steel-vertical-band-sealer-digital-control",
    packVerb: "Seals",
    worksWith: ["FP-101", "FP-103", "FP-106", "FP-109"],
  },
  {
    slug: "induction-cap-sealer",
    name: "Induction Cap Sealer",
    category: "sealing",
    priceFrom: 6600,
    priceTo: 161000,
    output: "Handheld to conveyor operation",
    bestFor: "Oils, sauces, supplements, cosmetics and other capped containers",
    summary: "Bonds a foil liner to a compatible bottle or jar neck for leak resistance and tamper evidence.",
    features: ["Handheld and continuous variants", "For compatible PET, HDPE or glass containers", "Container, cap and liner must be tested together"],
    image: "/images/machinery/catalog/induction-sealer.webp",
    imageAlt: "Representative inline induction cap sealing machine",
    sourceUrl: "https://www.newvisionmachines.com/shop/online-induction-cap-sealing-machine-20-130mm",
    packVerb: "Seals",
    worksWith: ["BC-201", "BC-202", "BC-204", "BC-214"],
  },
  {
    slug: "vacuum-packaging-machine",
    name: "Floor-standing External Vacuum Sealer",
    category: "sealing",
    priceFrom: 43500,
    priceTo: 220000,
    output: "Semi-automatic nozzle vacuum and seal",
    bestFor: "Rice, grains, coffee, dry fruits and larger food bags that will not fit a chamber",
    summary: "Draws air out of the pouch through a nozzle, then heat-seals it on a clamped sealing bar.",
    features: ["Fold-out shelf supports heavier bags", "Stainless-steel cabinet on castors", "Nitrogen flushing available on selected models"],
    image: "/images/machinery/catalog/vacuum-sealer.webp",
    imageAlt: "Floor-standing external vacuum sealing machine with fold-out bag shelf",
    sourceUrl: "https://www.ashvanipackaging.in/vacuum-packaging-machine.html",
    packVerb: "Seals",
    worksWith: ["FP-106", "FP-110", "FP-103"],
  },
  {
    slug: "cup-sealing-machine",
    name: "Cup & Tray Sealing Machine",
    category: "sealing",
    priceFrom: 38000,
    priceTo: 150000,
    output: "Semi-automatic cup sealing",
    bestFor: "Yoghurt, beverages, dips, ready food and portion packs",
    summary: "Heat-seals compatible lidding film to preformed cups and trays for a clean, tamper-evident closure.",
    features: ["Interchangeable cup dies", "Printed-film registration on selected models", "Pack and film compatibility tested before quote"],
    image: "/images/machinery/catalog/cup-sealer.webp",
    imageAlt: "Representative semi-automatic cup sealing machine",
    sourceUrl: "https://www.newvisionmachines.com/shop/semi-automatic-cup-sealing-machine-b9",
    packVerb: "Seals",
    worksWith: ["SP-912", "SP-907", "RL-704"],
  },
  {
    slug: "powder-filling-machine",
    name: "Powder & Granule Filler",
    category: "filling",
    priceFrom: 21000,
    priceTo: 170000,
    output: "Small batches to semi-automatic lines",
    bestFor: "Spices, powders, tea, coffee, grains and free-flowing products",
    summary: "Measures a set dose into a pouch, jar or container before it moves to the sealing step.",
    features: ["Auger or weighing configuration", "Fill range selected around product density", "Pairs with a band or induction sealer"],
    image: "/images/machinery/catalog/powder-filler.webp",
    imageAlt: "Representative bench-top powder and granule filling machine",
    sourceUrl: "https://www.newvisionmachines.com/shop/100-gram-filling-machine-for-powder",
    packVerb: "Fills",
    worksWith: ["FP-101", "FP-103", "BC-201", "BC-209"],
  },
  {
    slug: "paste-filling-machine",
    name: "Pneumatic Paste Filler",
    category: "filling",
    priceFrom: 34700,
    priceTo: 150000,
    output: "10–1,000 ml semi-automatic filling",
    bestFor: "Sauces, spreads, creams, gels and viscous products",
    summary: "Uses a piston to meter repeatable doses of thicker products into jars, bottles or suitable pouches.",
    features: ["Volume set by cylinder stroke", "Pedal or automatic cycle", "Hopper and nozzle selected for viscosity"],
    image: "/images/machinery/catalog/paste-filler.webp",
    imageAlt: "Representative stainless-steel pneumatic paste filling machine",
    sourceUrl: "https://www.newvisionmachines.com/shop/semi-automatic-pneumatic-paste-filling-machine-10-1000ml",
    packVerb: "Fills",
    worksWith: ["BC-201", "BC-202", "FP-104", "BC-204"],
  },
  {
    slug: "tube-filling-sealing-machine",
    name: "Semi-automatic Tube Filler & Sealer",
    category: "filling",
    priceFrom: 190000,
    priceTo: 500000,
    output: "Rotary table, operator-loaded tubes",
    bestFor: "Creams, gels, ointments, toothpaste and cosmetic tubes",
    summary: "Fills each tube from a heated or plain hopper, then seals and trims the open end on the same rotary table.",
    features: ["Hot-air sealing for plastic and laminated tubes", "Tube diameter set with holder change parts", "Batch-code crimp on selected models"],
    image: "/images/machinery/catalog/tube-filler.webp",
    imageAlt: "Semi-automatic rotary tube filling and sealing machine with hopper",
    sourceUrl: "https://www.newvisionmachines.com/blog/tube-filling-and-sealing-machine-price-in-india",
    packVerb: "Fills & seals",
    worksWith: ["TS-306", "TS-301"],
  },
  {
    slug: "liquid-filling-machine",
    name: "Double-head Liquid Filler",
    category: "filling",
    priceFrom: 56000,
    priceTo: 400000,
    output: "One or two-nozzle filling",
    bestFor: "Oils, syrups, beverages, shampoos and sanitisers",
    summary: "Meters low to medium-viscosity liquids into bottles, jars and compatible pouches.",
    features: ["Single and twin-nozzle options", "Food-contact parts specified by application", "Manual, pedal or timed cycle"],
    image: "/images/machinery/catalog/liquid-filler.webp",
    imageAlt: "Representative double-head semi-automatic liquid filling machine",
    sourceUrl: "https://www.newvisionmachines.com/shop/liquid-filling-machine-1000ml-double-head",
    packVerb: "Fills",
    worksWith: ["BC-201", "BC-202", "BC-214", "FP-104"],
  },
  {
    slug: "handheld-batch-coder",
    name: "Handheld Batch & Date Coder",
    category: "coding",
    priceFrom: 7999,
    priceTo: 35600,
    output: "Handheld and compact-line coding",
    bestFor: "MRP, batch, packed-on and expiry details on packs and cartons",
    summary: "Prints variable production information on compatible film, paper, board or labels.",
    features: ["Thermal inkjet and roller options", "Test ink adhesion on the final substrate", "Conveyor mounting available on selected models"],
    image: "/images/machinery/catalog/handheld-coder.webp",
    imageAlt: "Representative handheld thermal inkjet batch coding printer",
    sourceUrl: "https://www.newvisionmachines.com/shop/handheld-inkjet-printer-usb-portable-12-7mm",
    packVerb: "Codes",
    worksWith: ["BX-401", "FP-101", "LC-816", "EC-501"],
  },
  {
    slug: "inline-batch-coder",
    name: "Inline Batch Coding Printer",
    category: "coding",
    priceFrom: 15500,
    priceTo: 125000,
    output: "Continuous conveyor coding",
    bestFor: "Growing lines printing MRP, lot, date and QR information",
    summary: "Adds variable data as packs move down a conveyor, reducing manual handling at higher volumes.",
    features: ["Adjustable print heads", "Line-speed synchronisation", "Ink and adhesion verified against the substrate"],
    image: "/images/machinery/catalog/online-coder.webp",
    imageAlt: "Representative inline thermal inkjet batch coding system",
    sourceUrl: "https://www.newvisionmachines.com/shop/high-speed-automatic-batch-coding-inkjet-printer-online-tij-2-5",
    packVerb: "Codes",
    worksWith: ["BX-401", "FP-101", "LC-816", "EC-501"],
  },
  {
    slug: "semi-automatic-labelling-machine",
    name: "Semi-automatic Flat Surface Labeller",
    category: "coding",
    priceFrom: 49000,
    priceTo: 150000,
    output: "Pedal-operated, one pack at a time",
    bestFor: "Flat faces of pouches, cartons, tins and flat bottles",
    summary: "Peels a pressure-sensitive label from the roll and presses it flat onto the pack for consistent placement.",
    features: ["Pneumatic press plate with foot pedal", "Label roll and gap must match the sensor", "Fixture set to the pack size"],
    image: "/images/machinery/catalog/bottle-labeller.webp",
    imageAlt: "Semi-automatic flat surface labelling machine with pneumatic press and foot pedal",
    sourceUrl: "https://www.newvisionmachines.com/shop/flat-bottle-labelling-machine-automatic",
    packVerb: "Applies",
    worksWith: ["LC-814", "LC-804", "LC-805", "FP-101"],
  },
  {
    slug: "ropp-capping-machine",
    name: "Semi-automatic ROPP Capper",
    category: "sealing",
    priceFrom: 37000,
    priceTo: 88000,
    output: "Single-head bottle capping",
    bestFor: "Glass and rigid bottles using aluminium ROPP caps",
    summary: "Rolls and seals compatible metal caps onto filled bottles for a consistent closure.",
    features: ["Bottle and cap trial required", "Change parts selected to neck finish", "Pedal and semi-automatic options"],
    image: "/images/machinery/catalog/ropp-capper.webp",
    imageAlt: "Representative semi-automatic ROPP bottle capping machine",
    sourceUrl: "https://www.newvisionmachines.com/shop/semi-automatic-ropp-cap-sealing-machine",
    packVerb: "Caps",
    worksWith: ["BC-202"],
  },
  {
    slug: "vffs-pouch-packing-machine",
    name: "Automatic VFFS Pouch Line",
    category: "automatic",
    priceFrom: 170000,
    priceTo: 1800000,
    output: "Automatic form, fill and seal",
    bestFor: "Higher-volume powders, grains, pulses, snacks and compatible liquid products",
    summary: "Forms a pouch from printed rollstock, doses the product and seals it in one production cycle.",
    features: ["Filler selected for powder, granule or liquid", "Film width and registration set to the machine", "Advanced multihead systems are quoted above this band"],
    image: "/images/machinery/catalog/vffs-line.webp",
    imageAlt: "Representative automatic vertical form fill and seal machine",
    sourceUrl: "https://www.newvisionmachines.com/shop/1000-gram-ffs-machine-for-granule",
    packVerb: "Runs",
    worksWith: ["RL-701", "FP-112", "FP-105"],
  },
  {
    slug: "horizontal-flow-wrap-machine",
    name: "Horizontal Flow-wrap Machine",
    category: "automatic",
    priceFrom: 590000,
    priceTo: 1200000,
    output: "Automatic pillow-pack wrapping",
    bestFor: "Bars, bakery, soap, produce and regular solid products",
    summary: "Feeds individual products through printed rollstock, forms a pillow pack and seals it continuously.",
    features: ["Product pitch and film width configured together", "Registration control for printed film", "Infeed design matched to product handling"],
    image: "/images/machinery/catalog/flow-wrapper.webp",
    imageAlt: "Representative automatic horizontal flow-wrap packaging machine",
    sourceUrl: "https://www.newvisionmachines.com/shop/automatic-horizontal-flow-wrap-machine-for-pillow-packs",
    packVerb: "Runs",
    worksWith: ["RL-701", "FP-112"],
  },
  {
    slug: "shrink-wrapping-line",
    name: "Shrink-wrapping Line",
    category: "automatic",
    priceFrom: 250000,
    priceTo: 450000,
    output: "Bundling and secondary wrapping",
    bestFor: "Bottle multipacks, cartons and transit bundles",
    summary: "Wraps grouped products in shrink film and passes them through a controlled heat tunnel.",
    features: ["Web sealer and tunnel configured as a set", "Film selected around load and transport", "Manual to automatic infeed options"],
    image: "/images/machinery/catalog/shrink-wrapper.webp",
    imageAlt: "Representative web sealer and shrink tunnel line",
    sourceUrl: "https://www.newvisionmachines.com/shop/semi-automatic-web-sealer-shrink-wrapping-machine",
    packVerb: "Wraps with",
    worksWith: ["RL-705", "EC-502", "BC-201"],
  },
  {
    slug: "pallet-stretch-wrapper",
    name: "Pallet Stretch Wrapper",
    category: "automatic",
    priceFrom: 50000,
    priceTo: 400000,
    output: "Stable pallet loads for dispatch",
    bestFor: "Factories and warehouses shipping repeat pallet loads",
    summary: "Applies controlled stretch film around a completed pallet before storage or freight.",
    features: ["Turntable and arm configurations", "Wrap programme set to load stability", "Film pre-stretch options"],
    image: "/images/machinery/catalog/pallet-wrapper.webp",
    imageAlt: "Representative semi-automatic pallet stretch wrapping machine",
    sourceUrl: "https://www.newvisionmachines.com/shop/semi-automatic-pallet-stretch-wrapping-machine",
    packVerb: "Wraps pallets of",
    worksWith: ["EC-502", "BX-401"],
  },
];

export const STARTER_LINES = [
  {
    title: "Dry-food sealing line",
    budget: [18500, 82100] as const,
    machines: ["horizontal-band-sealer", "handheld-batch-coder"],
    packs: ["FP-101", "FP-106"],
    note: "Fill by hand, then seal and code pre-made pouches.",
  },
  {
    title: "Dry-product fill line",
    budget: [39500, 252100] as const,
    machines: ["powder-filling-machine", "vertical-band-sealer", "handheld-batch-coder"],
    packs: ["FP-101", "FP-103"],
    note: "Weigh, fill, seal and code spices, grains, tea or coffee.",
  },
  {
    title: "Liquid bottle line",
    budget: [91500, 461000] as const,
    machines: ["liquid-filling-machine", "induction-cap-sealer", "semi-automatic-labelling-machine"],
    packs: ["BC-201", "LC-814"],
    note: "Fill, induction-seal and label compatible bottles or jars.",
  },
  {
    title: "Automatic pouch line",
    budget: [178000, 1835600] as const,
    machines: ["vffs-pouch-packing-machine", "inline-batch-coder"],
    packs: ["RL-701"],
    note: "Move from printed rollstock to filled, sealed and coded pouches.",
  },
];

export function getMachine(slug: string) {
  return MACHINES.find((machine) => machine.slug === slug);
}

export function formatLakhRange(from: number, to: number) {
  return `${moneyCompact(from)} – ${moneyCompact(to)}`;
}
